image: microsoft/dotnet:latest

# ---------------------------------------
# Global
# ---------------------------------------

stages:
  - "Build"
  - "Tests"
  - "Package"
  - "Deploy"

variables:
  CI: "true"

# ----------------------------------------
# Prescript
# ----------------------------------------

# ----------------------------------------
# Build
# ----------------------------------------

build:
  stage: "Build"
  script:
    - sh build/build.sh
  artifacts:
    expire_in: 60 minutes
    paths:
      - artifacts/
  only:
    - web
    - develop
    - master

# ----------------------------------------
# Tests
# ----------------------------------------

unit tests:
  stage: "Tests"
  script:
    - sh build/test.sh
  dependencies:
    - build
  only:
    - web
    - develop
    - master

# ----------------------------------------
# Package
# ----------------------------------------

package:
  stage: "Package"
  script:
    - sh build/package.sh
  dependencies:
    - build
  artifacts:
    expire_in: 4 weeks
    paths:
      - artifacts/*.nupkg
  only:
    - web
    - develop
    - master

# ----------------------------------------
# Deploy
# ----------------------------------------

deploy:
  stage: "Deploy"
  script:
    - sh build/deploy.sh
  dependencies:
    - package
  only:
    - tags